# Generated by Django 2.2.5 on 2019-12-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('carrying_capacity', models.FloatField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='api.Car')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weight', models.FloatField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_list', to='api.Car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_list', to='api.Client')),
                ('finish_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_list_finish', to='api.City')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_list_start', to='api.City')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
    ]
